# Generated by Django 5.1.1 on 2024-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewee_interview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='interview_identity',
            field=models.IntegerField(choices=[(1, '候场引导'), (2, '面试官'), (3, '围观')], default=3),
        ),
    ]
