# Generated by Django 5.1.1 on 2024-09-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='status',
            field=models.IntegerField(choices=[(1, '正在进行面试'), (2, '正在进行录取')], default=1),
        ),
    ]
