# Generated by Django 5.1.1 on 2024-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_judgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='interview_identity',
            field=models.IntegerField(choices=[(1, '候场引导'), (2, '面试官'), (3, '围观群众')]),
        ),
    ]
