# Generated by Django 5.1.1 on 2024-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_alter_interviewer_interview_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewee',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
