# Generated by Django 5.2.6 on 2025-09-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_interviewee_end_datetime_interviewee_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='ability',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], help_text='1-5星评分', verbose_name='专业能力'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='cognition',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], help_text='1-5星评分', verbose_name='对网协的认识'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='representation',
            field=models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], help_text='1-5星评分', verbose_name='表达能力'),
        ),
    ]
