# Generated by Django 5.2.6 on 2025-09-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_alter_judgement_ability_alter_judgement_cognition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
